//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Assets.Culture {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ja_JP {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Assets.Culture.Resources.ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to アプリについて.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 開発者について.
        /// </summary>
        internal static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新をチェック.
        /// </summary>
        internal static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to テーマ.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ダーク.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ライト.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to システム.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョンが利用可能です。今すぐインストールしますか？.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 現在、利用可能な更新はありません。.
        /// </summary>
        internal static string UpdateNotAvailable {
            get {
                return ResourceManager.GetString("UpdateNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新情報の取得に失敗しました。しばらく後にお試しください。.
        /// </summary>
        internal static string updateUnable {
            get {
                return ResourceManager.GetString("updateUnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 表示.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
