//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Assets.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Assets.Culture.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Developer.
        /// </summary>
        public static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (min).
        /// </summary>
        public static string CaptureInterval {
            get {
                return ResourceManager.GetString("CaptureInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a decimal number.
        /// </summary>
        public static string CaptureIntervalError {
            get {
                return ResourceManager.GetString("CaptureIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the path to client_secrets.json.
        /// </summary>
        public static string EnterGoogleSecretFilePath {
            get {
                return ResourceManager.GetString("EnterGoogleSecretFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Sheet ID.
        /// </summary>
        public static string GoogleSheetId {
            get {
                return ResourceManager.GetString("GoogleSheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Sheet Name.
        /// </summary>
        public static string GoogleSheetName {
            get {
                return ResourceManager.GetString("GoogleSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Folder.
        /// </summary>
        public static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit App.
        /// </summary>
        public static string QuitApp {
            get {
                return ResourceManager.GetString("QuitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Google Authentication File.
        /// </summary>
        public static string RegisterGoogleAuthFile {
            get {
                return ResourceManager.GetString("RegisterGoogleAuthFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your Google data in the settings.
        /// </summary>
        public static string RegisterGoogleDataWarning {
            get {
                return ResourceManager.GetString("RegisterGoogleDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Google Sheet Data.
        /// </summary>
        public static string RegisterGoogleSheetData {
            get {
                return ResourceManager.GetString("RegisterGoogleSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been completed..
        /// </summary>
        public static string RegistrationComplete {
            get {
                return ResourceManager.GetString("RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is required.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app for changes to take effect?.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available! Update now?.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no update available..
        /// </summary>
        public static string UpdateNotAvailable {
            get {
                return ResourceManager.GetString("UpdateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine update status..
        /// </summary>
        public static string UpdateUnable {
            get {
                return ResourceManager.GetString("UpdateUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string UploadInterval {
            get {
                return ResourceManager.GetString("UploadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily at midnight (12:00 AM).
        /// </summary>
        public static string UploadInterval_1 {
            get {
                return ResourceManager.GetString("UploadInterval_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a day (midnight, noon).
        /// </summary>
        public static string UploadInterval_2 {
            get {
                return ResourceManager.GetString("UploadInterval_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 8 hours.
        /// </summary>
        public static string UploadInterval_3 {
            get {
                return ResourceManager.GetString("UploadInterval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 hours.
        /// </summary>
        public static string UploadInterval_4 {
            get {
                return ResourceManager.GetString("UploadInterval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
