//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Assets.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Assets.Culture.Resources.ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリについて.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開発者について.
        /// </summary>
        internal static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参照.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャプチャ.
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 間隔（分）.
        /// </summary>
        internal static string CaptureInterval {
            get {
                return ResourceManager.GetString("CaptureInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10進数である必要があります.
        /// </summary>
        internal static string CaptureIntervalError {
            get {
                return ResourceManager.GetString("CaptureIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新をチェック.
        /// </summary>
        internal static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_secrets.json のパスを入力してください.
        /// </summary>
        internal static string EnterGoogleSecretFilePath {
            get {
                return ResourceManager.GetString("EnterGoogleSecretFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleシートID.
        /// </summary>
        internal static string GoogleSheetId {
            get {
                return ResourceManager.GetString("GoogleSheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googleシート名.
        /// </summary>
        internal static string GoogleSheetName {
            get {
                return ResourceManager.GetString("GoogleSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力フォルダ.
        /// </summary>
        internal static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力フォルダ.
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効なパス.
        /// </summary>
        internal static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プレビュー.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリを終了.
        /// </summary>
        internal static string QuitApp {
            get {
                return ResourceManager.GetString("QuitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google認証ファイルの登録.
        /// </summary>
        internal static string RegisterGoogleAuthFile {
            get {
                return ResourceManager.GetString("RegisterGoogleAuthFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定画面からGoogleデータの登録をしてください.
        /// </summary>
        internal static string RegisterGoogleDataWarning {
            get {
                return ResourceManager.GetString("RegisterGoogleDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googleシートデータの登録.
        /// </summary>
        internal static string RegisterGoogleSheetData {
            get {
                return ResourceManager.GetString("RegisterGoogleSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録が完了しました。.
        /// </summary>
        internal static string RegistrationComplete {
            get {
                return ResourceManager.GetString("RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必須です.
        /// </summary>
        internal static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更を有効にするためにアプリを再起動しますか？.
        /// </summary>
        internal static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマ.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダーク.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ライト.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システム.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョンが利用可能です。今すぐインストールしますか？.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新が完了しました。.
        /// </summary>
        internal static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、利用可能な更新はありません。.
        /// </summary>
        internal static string UpdateNotAvailable {
            get {
                return ResourceManager.GetString("UpdateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新情報の取得に失敗しました。しばらく後にお試しください。.
        /// </summary>
        internal static string UpdateUnable {
            get {
                return ResourceManager.GetString("UpdateUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 間隔.
        /// </summary>
        internal static string UploadInterval {
            get {
                return ResourceManager.GetString("UploadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毎日深夜（午前0時）.
        /// </summary>
        internal static string UploadInterval_1 {
            get {
                return ResourceManager.GetString("UploadInterval_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1日2回（深夜、正午）.
        /// </summary>
        internal static string UploadInterval_2 {
            get {
                return ResourceManager.GetString("UploadInterval_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8時間ごと.
        /// </summary>
        internal static string UploadInterval_3 {
            get {
                return ResourceManager.GetString("UploadInterval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6時間ごと.
        /// </summary>
        internal static string UploadInterval_4 {
            get {
                return ResourceManager.GetString("UploadInterval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
